# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates
version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/typed_floats"
    schedule:
      interval: "weekly"
  - package-ecosystem: "cargo"
    directory: "/typed_floats_macros"
    schedule:
      interval: "weekly"
