[workspace]

members = [
    "typed_floats",
    "typed_floats_macros",
    "typed_floats_tests",
]

resolver = "2"

[profile.dev]
# To avoid creating +1GB incremental artifacts
incremental = false

[profile.test]
incremental = false

[profile.release]
panic = "abort"