[workspace]

members = [
    "typed_floats",
    "typed_floats_macros",
    "typed_floats_tests",
]

[profile.dev]
incremental = false

[profile.test]
incremental = false

[profile.release]
panic = "abort"