[workspace]
members = ["xtask", "typed_floats", "typed_floats_macros"]
resolver = "2"

[workspace.package]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/tdelmas/typed_floats"
version = "1.0.1-dev"
rust-version = "1.70"
