[build]

publish = "./target/doc/"
command = "rustup default nightly && cargo xtask pre-build && cd typed_floats && cargo doc --all-features"

[[redirects]]
from = "/"
to = "/typed_floats/"
status = 302
