
jobs:
  build_and_test:
    docker:
      - image: cimg/rust:1.70.0
    steps:
      - checkout
      - run: ./test.sh
  build_and_test_arm:
    machine:
      image: ubuntu-2004:current 
    resource_class: arm.medium
    steps:
      - checkout
      - run: ./test.sh

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - build_and_test_arm