version: 2.1

executors:
  docker:
    docker:
      - image: cimg/rust:1.70.0
  arm:
    machine:
      image: ubuntu-2004:current 
    resource_class: arm.medium
    environment:
      INSTALL_CMD: curl https://sh.rustup.rs -sSf | sh -s -- -y

jobs:
  build_and_test:
    parameters:
      executor:
        type: executor
      version:
        type: string
      release:
        type: string
      features:
        type: string
    executor: << parameters.executor >>
    steps:
      - checkout
      - run: if [ -z "$INSTALL_CMD" ]; then $INSTALL_CMD; fi
      - run: rustup default ${{ matrix.version }}
      - run: cargo xtask pre-build
      - run: cd typed_floats && cargo build --no-default-features --features "${{ matrix.features }}" ${{ matrix.release }}
      - run: cd typed_floats && cargo test --no-default-features --features "${{ matrix.features }}" ${{ matrix.release }}

workflows:
  build_and_test:
    jobs:
      - build_and_test:
          matrix:
            parameters:
              executor: [docker, arm]
              version: [
                "beta",
                "stable",
                "1.70",
              ]
              release: [
                "",
                "--release",
              ]
              features: [
                  "",
                  "std",
                  "serde",
                  "libm",
                  "std,serde",
                  "std,libm",
                  "serde,libm",
                  "std,serde,libm",
              ]
