
jobs:
  build_and_test:
    docker:
      - image: cimg/rust:1.70.0
    steps:
      - checkout
      - run: cargo test
  build_and_test_arm:
    machine:
      image: ubuntu-2004:current 
    resource_class: arm.medium
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: cargo test
  build_and_test_macos:
    macos:
      xcode: 14.2.0
    resource_class: macos.x86.medium.gen2
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: cargo test

  build_and_test_m1:
    macos:
      xcode: 14.2.0
    resource_class: macos.m1.medium.gen1
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: cargo test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - build_and_test_arm
      - build_and_test_macos
      - build_and_test_m1