
jobs:
  build_and_test:
    docker:
      - image: cimg/rust:1.70.0
    steps:
      - checkout
      - run: cargo xtask pre-build
      - run: cargo test
      - run: cargo test --no-default-features
      - run: cargo test --verbose --features serde
      - run: cargo test --test 'serde' --no-default-features --features serde
      - run: cargo test --no-default-features --features libm
      - run: cargo build --no-default-features --features serde,std,libm
  build_and_test_arm:
    machine:
      image: ubuntu-2004:current 
    resource_class: arm.medium
    steps:
      - checkout
      - run: curl https://sh.rustup.rs -sSf | sh -s -- -y
      - run: cargo xtask pre-build
      - run: cargo test
      - run: cargo test --no-default-features
      - run: cargo test --verbose --features serde
      - run: cargo test --test 'serde' --no-default-features --features serde
      - run: cargo test --test 'serde' --no-default-features --features serde,libm
      - run: cargo test --test 'serde' --no-default-features --features serde,libm,std
      - run: cargo test --no-default-features --features libm
      - run: cargo build --no-default-features --features serde,std,libm

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_and_test
      - build_and_test_arm