[package]
categories = ["mathematics", "data-structures"]
description = "Types for handling floats with type checking at compile time."
edition = "2021"
include = [
  "Cargo.toml",
  "src/*.rs",
  "*.md",
]
keywords = ["floats", "non-zero", "NaN"]
license = "MIT OR Apache-2.0"
name = "typed_floats"
readme = "./README.md"
repository = "https://github.com/tdelmas/typed_floats"
version = "0.1.35"

[dependencies]
serde_json = {version = "1.0"}
thiserror = "1.0"
num = "0.4"
typed_floats_macros = {version = "=0.1.35", path = "../typed_floats_macros"}
