[package]
description = "Types for handling floats with type checking at compile time."
edition = "2021"
include = [
  "Cargo.toml",
  "src/*.rs",
  "*.md",
]
keywords = ["float"]
license = "MIT OR Apache-2.0"
name = "typed_floats"
readme = "./README.md"
repository = "https://github.com/tdelmas/floats"
version = "0.1.30"
categories = ["mathematics", "data-structures"]

[dependencies]
serde_json = {version = "1.0"}
thiserror = "1.0"
typed_floats_macros = {version = "=0.1.30", path = "../typed_floats_macros"}
