[package]
categories = ["mathematics", "data-structures"]
description = "Types for handling floats with type checking at compile time."
edition = "2021"
include = [
  "Cargo.toml",
  "src/*.rs",
  "src/**/*.rs",
  "*.md",
]
keywords = ["floats", "non-zero", "nan", "no_std"]
license = "MIT OR Apache-2.0"
name = "typed_floats"
readme = "./README.md"
repository = "https://github.com/tdelmas/typed_floats"
version = "0.7.3"
rust-version = "1.70"

[features]
default = ["std", "compiler_hints"]
# follows each debug_assert! with core::hint::unreachable_unchecked
compiler_hints = []
serde = ["dep:serde"]
std = ["typed_floats_macros/std"]
libm = ["dep:num-traits", "typed_floats_macros/libm"]

[dependencies]

[dependencies.typed_floats_macros]
version = "=0.7.3"
path = "../typed_floats_macros"

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive"]
optional = true

[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["libm"]
optional = true

[dev-dependencies]
serde_json = { version = "1.0" }
num-traits = "0.2"

[package.metadata.docs.rs]
features = ["serde"]
