[package]
name = "typed_floats"
description = "Types for handling floats with type checking at compile time."
categories = ["mathematics", "data-structures"]
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
include = [
  "Cargo.toml",
  "src/*.rs",
  "src/**/*.rs",
  "*.md",
]
keywords = ["floats", "non-zero", "nan", "no_std"]
readme = "./README.md"
rust-version.workspace = true

[features]
default = ["std", "compiler_hints"]
# follows each debug_assert! with core::hint::unreachable_unchecked
compiler_hints = []
# Add the `serde` dependency to enable serialization and deserialization of the types.
serde = ["dep:serde"]
# Allow to switch between `std` and `no_std` environments.
std = ["typed_floats_macros/std"]
# Add the the `num-traits` dependency to have access to most math functions in `no_std` environments.
libm = ["dep:num-traits", "typed_floats_macros/libm"]
pyo3 = ["dep:pyo3"]
napi = ["dep:napi", "dep:napi-derive"]

[dependencies]

[dependencies.typed_floats_macros]
version = "=0.7.4"
path = "../typed_floats_macros"

[dependencies.serde]
version = "1.0"
default-features = false
features = ["derive"]
optional = true

[dependencies.num-traits]
version = "0.2"
default-features = false
features = ["libm"]
optional = true

[dependencies.napi]
version = "2.13"
default-features = false
#features = ["napi6"]
optional = true

[dependencies.napi-derive]
version = "2.13"
optional = true

[dependencies.pyo3]
version = "0.20"
#features = ["serde"]
optional = true

[dev-dependencies]
serde_json = { version = "1.0" }
num-traits = "0.2"

[package.metadata.docs.rs]
features = ["serde"]
