[package]
name = "typed_floats"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Types for handling floats with type checking at compile time."

[dependencies]
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0"}
thiserror = "1.0"
typed_floats_macros = { version = "0.1.0", path = "../typed_floats_macros" }

[features]
serde = ["dep:serde"]
