[package]
categories = ["mathematics", "data-structures"]
description = "Types for handling floats with type checking at compile time."
edition = "2021"
include = [
  "Cargo.toml",
  "src/*.rs",
  "*.md",
]
keywords = ["floats", "non-zero", "NaN"]
license = "MIT OR Apache-2.0"
name = "typed_floats"
readme = "./README.md"
repository = "https://github.com/tdelmas/typed_floats"
version = "0.1.37"

[features]
default = ["std", "num"]
# The absence of this feature is not yet stable
std = []
# The absence of this feature is not yet stable
num = ["dep:num"]

[dependencies]
thiserror = "1.0"
num = {version = "0.4", optional = true}
typed_floats_macros = {version = "=0.1.37", path = "../typed_floats_macros"}

[dev-dependencies]
# For examples
checked-float = "0.1.4"
ordered-float = "4.1.0"