[package]
name = "typed_floats_macros"
version = "0.1.6"
edition = "2021"
license = "MIT OR Apache-2.0"
description = "Crate only used to generate the `typed_floats` crate."
repository = "https://github.com/tdelmas/floats"
readme = "./README.md"

[profile.dev]
incremental = false

[profile.test]
incremental = false

[lib]
proc-macro = true

[dependencies]
quote = "1.0"
syn = { version = "2.0", features = ["extra-traits"] }
proc-macro2 = "1.0"
