name: Check docs

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 

jobs:
  check-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: cargo install lychee 
      - run: cargo xtask pre-build
      - run: cd typed_floats && cargo doc --all-features
      - run: lychee --offline "./target/doc/typed_floats/**/*.html"
