name: Exaustive Tests

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests on rust ${{ matrix.version }} features "${{ matrix.features }}"
    strategy:
      matrix:
        version: [
          "beta",
          "stable",
          "1.70",
        ]
        release: [
          "",
          "--release",
        ]
        features: [
            "",
            "std",
            "serde",
            "libm",
            "std,serde",
            "std,libm",
            "serde,libm",
            "std,serde,libm",
        ]

    steps:
      - uses: actions/checkout@v3
      - run: rustup default ${{ matrix.version }}
      - run: cargo xtask pre-build
      - run: cd typed_floats && cargo build --no-default-features --features "${{ matrix.features }}" ${{ matrix.release }}
      - run: cd typed_floats && cargo test --no-default-features --features "${{ matrix.features }}" ${{ matrix.release }}
