name: Miri

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 

jobs:
  miri:
    runs-on: ubuntu-latest
    name: Miri

    steps:
      - uses: actions/checkout@v3
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
          cargo install nextest
      - run: cargo xtask pre-build
      - run: cargo miri test --doc
      - run: cargo miri nextest run -j128

          