on:
  push:
    tags:
      - "*"
  workflow_dispatch:

name: Publish

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: cargo publish typed_floats_macros
        run: cd typed_floats_macros && cargo publish --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
      - name: cargo publish typed_floats
        run: |
          rustup toolchain install nightly
          echo "Running pre-publish.rs..."
          cargo +nightly -Zscript ./pre-publish.rs 
          cd typed_floats
          ls -la
          cargo publish --allow-dirty --token ${CRATES_TOKEN}
        env:
          CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
  