name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          du -sh
          cargo +nightly -Zscript .\pre-publish.rs
          cargo build --verbose
          du -sh
      - name: Run tests
        run: |
          du -sh
          cargo +nightly -Zscript .\pre-publish.rs
          cargo test --verbose
          du -sh
      - name: Run clippy
        run: cargo clippy --verbose
