name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests on rust toolchain ${{ matrix.version }}
    strategy:
      matrix:
        version: [
          "nightly",
          "stable",
          "1.70",
          "1.56", # 2021 edition
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cargo xtask pre-build
          rustup toolchain install ${{ matrix.version }}
          cargo build
      - run: ./tests.sh
        
  clippy:
    runs-on: ubuntu-latest
    name: Clippy

    steps:
      - uses: actions/checkout@v3
      - run: |
          cargo xtask pre-build
          cargo clippy --verbose
