name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests on rust toolchain ${{ matrix.version }}
    strategy:
      matrix:
        version: [
          "nightly",
          "stable",
          "1.70",
          "1.56", # 2021 edition
        ]

    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          rustup toolchain install nightly
          cargo +nightly -Zscript ./pre-publish.rs
          rustup toolchain install ${{ matrix.version }}
          cargo build
      - name: Build tests
        run: cargo test --no-run
      - name: Run tests
        run: cargo test --verbose

  clippy:
    runs-on: ubuntu-latest
    name: Clippy

    steps:
      - uses: actions/checkout@v3
        run: |
          rustup toolchain install nightly
          cargo +nightly -Zscript ./pre-publish.rs
          cargo clippy --verbose
