name: Tests

on:
  push:
    branches: ["main"]
    paths:
    - 'typed_floats/**'
    - 'typed_floats_macros/**'
    - 'Cargo.toml'
    - 'Cargo.lock'
  pull_request:
    branches: ["main"]
    paths:
    - 'typed_floats/**'
    - 'typed_floats_macros/**'
    - 'Cargo.toml'
    - 'Cargo.lock'

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0 

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests on rust toolchain ${{ matrix.version }}
    strategy:
      matrix:
        version: [
          "beta",
          "stable",
          "1.70",
        ]

    steps:
      - uses: actions/checkout@v3
      - run: rustup default ${{ matrix.version }}
      - run: cargo --version
      - run: cargo xtask pre-build
      - run: cd typed_floats && ./tests-ci.sh
        
  clippy:
    runs-on: ubuntu-latest
    name: Clippy

    steps:
      - uses: actions/checkout@v3
      - run: cargo xtask pre-build
      - run: cargo clippy --verbose --all-features

  publish-dry-run:
    runs-on: ubuntu-latest
    name: Publish dry run

    steps:
      - uses: actions/checkout@v3
      - run: cargo xtask pre-build
      - run: cd typed_floats && cargo publish --allow-dirty --dry-run
    
  miri:
    runs-on: ubuntu-latest
    name: Miri

    steps:
      - uses: actions/checkout@v3
      - name: Install Miri
        run: |
          rustup toolchain install nightly --component miri
          rustup override set nightly
          cargo miri setup
      - run: cargo xtask pre-build
      - name: Test with Miri
        run: cargo miri test
        