name: Weekly tests on nightly/beta/stable

on:
  schedule:
    # Every Monday
    - cron:  '0 0 * * 1'
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    name: Tests on rust toolchain ${{ matrix.version }}
    strategy:
      matrix:
        version: [
          "nightly",
          "beta",
          "stable",
        ]

    steps:
      - uses: actions/checkout@v3
      - run: rustup default ${{ matrix.version }}
      - run: cargo --version
      - run: cargo xtask pre-build
      - run: cd typed_floats && ./tests-ci.sh
